# Site
repository: pseudocoding/about
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Devin Houde
title: Principal Engineer
email: dphoude7@email.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  pseudocoding
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: thenotoriousbatman
linkedin_username: dphoude
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Devin and I'm a principal engineer. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>NodeJS</mark> and <mark>Eating Pizza</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Optum
        link: optum.com
        # link_text: boringcompany.com
        sub_title: Principal Engineer
        caption: June 2012 - Present
        quote: >
          Solving healthcare problems through a DevOps culture
        description: | # this will include new lines to allow paragraphs
          Joined as a member of the Technology Development Program to work on Java and .NET applications servince healthcare needs and progressed towards automation through
          the use of CI/CD and the adoption of a DevOps culture.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Western New England University
        caption: 2009 - 2012
        sub_title: BS Computer Science
        quote: >
          Western New England University is much more than its educational offerings; its strength is found in the individuals who educate and support students to thrive in our learning community. We attract students who are hard working, ambitious, curious, and caring with a strong entrepreneurial spirit. They excel in our close-knit campus where they find the confidence to push their abilities to conquer new challenges and think critically about the world around them and their place in it. Join them and prepare to do more, achieve more, and be more than you ever imagined.
        description: | # this will include new lines to allow paragraphs
          While attending Western New England, I spent time working on deadlines and expanding my leadership skills. I learned a lot about how to lead efforts as well as balancing a social life.
          
          Much of my extra time was spent on a wide variets of clubs and committiees taking on roles such as _Campus Activities Board Travel Chair_, _Student Senate Class Represenative, _Spring Event Hospitality Chair_, _Peer Education Network Vice President_, and _Association for Computing Macinery President_

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Modding vehicles

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
